/** All known Keycloak event types with descriptions. */

export interface EventOption {
  value: string;
  description: string;
}

export const ALL_EVENT_OPTIONS: EventOption[] = [
  // Wildcards
  { value: '*', description: 'All events (access + admin)' },
  { value: 'access.*', description: 'All user/access events' },
  { value: 'admin.*', description: 'All admin events' },

  // Access events
  { value: 'access.LOGIN', description: 'User logs in successfully' },
  { value: 'access.LOGIN_ERROR', description: 'User login attempt fails' },
  { value: 'access.LOGOUT', description: 'User logs out' },
  { value: 'access.LOGOUT_ERROR', description: 'User logout fails' },
  { value: 'access.REGISTER', description: 'New user self-registers' },
  { value: 'access.REGISTER_ERROR', description: 'Self-registration fails' },
  { value: 'access.CODE_TO_TOKEN', description: 'Auth code exchanged for token (OIDC flow)' },
  { value: 'access.CODE_TO_TOKEN_ERROR', description: 'Auth code exchange fails' },
  { value: 'access.CLIENT_LOGIN', description: 'Service account (client credentials) login' },
  { value: 'access.CLIENT_LOGIN_ERROR', description: 'Service account login fails' },
  { value: 'access.REFRESH_TOKEN', description: 'Access token refreshed' },
  { value: 'access.REFRESH_TOKEN_ERROR', description: 'Token refresh fails' },
  { value: 'access.VALIDATE_ACCESS_TOKEN', description: 'Token validated via userinfo endpoint' },
  { value: 'access.INTROSPECT_TOKEN', description: 'Token introspected (active/inactive check)' },
  { value: 'access.FEDERATED_IDENTITY_LINK', description: 'User links an external identity provider' },
  { value: 'access.REMOVE_FEDERATED_IDENTITY', description: 'User unlinks an external identity provider' },
  { value: 'access.UPDATE_EMAIL', description: 'User changes their email' },
  { value: 'access.UPDATE_PROFILE', description: 'User updates their profile' },
  { value: 'access.UPDATE_PASSWORD', description: 'User changes their password' },
  { value: 'access.UPDATE_TOTP', description: 'User configures TOTP (2FA)' },
  { value: 'access.VERIFY_EMAIL', description: 'User verifies their email address' },
  { value: 'access.REMOVE_TOTP', description: 'User removes TOTP (2FA)' },
  { value: 'access.SEND_RESET_PASSWORD', description: 'Password reset email sent' },
  { value: 'access.RESET_PASSWORD', description: 'User resets password via link' },
  { value: 'access.RESET_PASSWORD_ERROR', description: 'Password reset fails' },
  { value: 'access.RESTART_AUTHENTICATION', description: 'Authentication flow restarted' },
  { value: 'access.IDENTITY_PROVIDER_LOGIN', description: 'Login via external identity provider' },
  { value: 'access.IDENTITY_PROVIDER_FIRST_LOGIN', description: 'First login via external identity provider' },
  { value: 'access.IDENTITY_PROVIDER_POST_LOGIN', description: 'Post-login processing after IdP auth' },
  { value: 'access.IMPERSONATE', description: 'Admin impersonates a user' },
  { value: 'access.CUSTOM_REQUIRED_ACTION', description: 'Custom required action executed' },
  { value: 'access.EXECUTE_ACTIONS', description: 'Admin triggers required actions for user' },
  { value: 'access.EXECUTE_ACTION_TOKEN', description: 'User completes an action token (email link)' },
  { value: 'access.CLIENT_REGISTER', description: 'Client registered via dynamic registration' },
  { value: 'access.CLIENT_UPDATE', description: 'Client updated via dynamic registration' },
  { value: 'access.CLIENT_DELETE', description: 'Client deleted via dynamic registration' },
  { value: 'access.CLIENT_INITIATED_ACCOUNT_LINKING', description: 'Client initiates account linking with IdP' },
  { value: 'access.TOKEN_EXCHANGE', description: 'Token exchanged (e.g. external-to-internal)' },
  { value: 'access.PERMISSION_TOKEN', description: 'UMA permission ticket issued' },

  // Admin events
  { value: 'admin.USER-CREATE', description: 'Admin creates a user' },
  { value: 'admin.USER-UPDATE', description: 'Admin updates user attributes' },
  { value: 'admin.USER-DELETE', description: 'Admin deletes a user' },
  { value: 'admin.CLIENT-CREATE', description: 'Admin creates a client (application)' },
  { value: 'admin.CLIENT-UPDATE', description: 'Admin updates a client configuration' },
  { value: 'admin.CLIENT-DELETE', description: 'Admin deletes a client' },
  { value: 'admin.REALM-UPDATE', description: 'Admin updates realm settings' },
  { value: 'admin.ROLE_MAPPING-CREATE', description: 'Admin assigns a realm role to a user' },
  { value: 'admin.ROLE_MAPPING-DELETE', description: 'Admin removes a realm role from a user' },
  { value: 'admin.CLIENT_ROLE_MAPPING-CREATE', description: 'Admin assigns a client role to a user' },
  { value: 'admin.CLIENT_ROLE_MAPPING-DELETE', description: 'Admin removes a client role from a user' },
  { value: 'admin.GROUP-CREATE', description: 'Admin creates a group' },
  { value: 'admin.GROUP-UPDATE', description: 'Admin updates a group' },
  { value: 'admin.GROUP-DELETE', description: 'Admin deletes a group' },
  { value: 'admin.GROUP_MEMBERSHIP-CREATE', description: 'Admin adds a user to a group' },
  { value: 'admin.GROUP_MEMBERSHIP-DELETE', description: 'Admin removes a user from a group' },
  { value: 'admin.IDENTITY_PROVIDER-CREATE', description: 'Admin creates an identity provider' },
  { value: 'admin.IDENTITY_PROVIDER-UPDATE', description: 'Admin updates an identity provider' },
  { value: 'admin.IDENTITY_PROVIDER-DELETE', description: 'Admin deletes an identity provider' },
  { value: 'admin.COMPONENT-CREATE', description: 'Admin creates a component (e.g. LDAP federation)' },
  { value: 'admin.COMPONENT-UPDATE', description: 'Admin updates a component' },
  { value: 'admin.COMPONENT-DELETE', description: 'Admin deletes a component' },
  { value: 'admin.AUTHORIZATION_RESOURCE-CREATE', description: 'Admin creates an authorization resource' },
  { value: 'admin.AUTHORIZATION_RESOURCE-UPDATE', description: 'Admin updates an authorization resource' },
  { value: 'admin.AUTHORIZATION_RESOURCE-DELETE', description: 'Admin deletes an authorization resource' },
  { value: 'admin.AUTHORIZATION_POLICY-CREATE', description: 'Admin creates an authorization policy' },
  { value: 'admin.AUTHORIZATION_POLICY-UPDATE', description: 'Admin updates an authorization policy' },
  { value: 'admin.AUTHORIZATION_POLICY-DELETE', description: 'Admin deletes an authorization policy' },
  { value: 'admin.AUTHORIZATION_SCOPE-CREATE', description: 'Admin creates an authorization scope' },
  { value: 'admin.AUTHORIZATION_SCOPE-UPDATE', description: 'Admin updates an authorization scope' },
  { value: 'admin.AUTHORIZATION_SCOPE-DELETE', description: 'Admin deletes an authorization scope' },
];
